### ISSUE TITLE
numpy==1.14.0 (one of the code requirements) did not work with python 3.7. Check?

### ISSUE THREAD

**Issue by higherdefender** [FIGLAB/ubicoustics#1]
You might want to direct users to install python 3.6 instead? That worked for me. 

Also, with python 3.6, there is no need to specify global_flags with pyaudio for portaudio.h etc. All dependencies are built into pyaudio installation.

**Comment by gierad** [comment]
Good find. I don't think I've ever tested the platform on python 3.7.  I'll modify the requirements. Stay tuned.

**Comment by gierad** [comment]
The general fix here is to force `virtualenv` to use `python3.6`:
```
virtualenv ./ubicoustics -p python3.6
source ubicoustics/bin/activate
```

**Comment by gierad** [comment]
I've updated the repo with the a strict `python3.6` version requirement.
